FROM ubuntu:18.04

RUN apt-get update

# install Faucet
RUN apt-get install python3-dev python3-pip -y \
    && pip3 install setuptools \
    && pip3 install wheel \
    && apt-get install wget git -y 

RUN pip3 install faucet

# Install faucetagent
COPY ./  /pegler/
RUN git clone https://github.com/faucetsdn/faucetagent.git \
    && cd /faucetagent && sed -i "s/sudo//g" dependencies.sh && ./dependencies.sh
RUN  cd /faucetagent && make

ExPOSE 6653

CMD faucet 

# You need to run gnmi agent using 
# sudo docker exec faucet ./faucetagent/faucetagent.py --cert /pegler/tls_cert_key/server/server.crt  --key /pegler/tls_cert_key/server/server.key --configfile /etc/faucet/faucet.yaml 
# sudo docker build -t shaboti/faucet-agent -f Dockerfile.faucet-agent .
